llm:
  provider: "openai"   
  model: "gpt-4o-mini" 
  temperature: 1.0
  max_tokens: 1000 
  deployment: "gpt-4.1"
  ##use_proxy: false
credentials:
  azure_openai_api_key: -
  azure_openai_endpoint: -
  azure_openai_api_version: -
app:
  language: "pt-BR"
  default_servings: 2
  default_time_minutes: 30
  enable_shopping_list_export: true
  enable_nutrition_estimate: true
